[package]
name = "unlock-puzzle-generator"
version = "1.0.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
serde = { version = "1.0.108", features = ["derive"] }
serde_json = "1.0.108"
chrono = "0.4"
